version: 2

build:
  image: latest

sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

submodules:
  include: all

# Don't build any extra formats
formats: []